package Customer;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rukshan
 */
public class Details extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Details
     */
    public Details() {
        con = sql_connect.connectDB();
        initComponents();
        fetch();
        this.setLocationRelativeTo(null);

    }

    public void fetch() {
        try {
            String q = "select * from Details";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();

            Details.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void clearFields() {
        UName.setText(null);
        UAdress.setText(null);
        UPhone.setText(null);
        UNIC.setText(null);
        UCustomerID.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Details = new javax.swing.JTable();
        Update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        searchBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UCustomerID = new javax.swing.JTextField();
        UName = new javax.swing.JTextField();
        UAdress = new javax.swing.JTextField();
        UPhone = new javax.swing.JTextField();
        UNIC = new javax.swing.JTextField();
        PIC = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Customer Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 60, 154, 22);

        Details.setAutoCreateRowSorter(true);
        Details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Address", "Phone no", "NIC", "Service Type", "Cus. ID"
            }
        ));
        Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Details);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 1010, 120);

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update);
        Update.setBounds(900, 410, 90, 29);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(10, 230, 80, 29);

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(690, 440, 65, 29);

        jButton5.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton5.setText("Customer Registation");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(20, 400, 173, 23);

        jButton8.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton8.setText("Report");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(20, 430, 170, 23);

        jButton7.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton7.setText("Loayalties");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(200, 430, 200, 23);

        jButton9.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton9.setText("Active /Inactive member");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(200, 400, 200, 23);

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(630, 440, 59, 29);

        searchBox.setForeground(new java.awt.Color(204, 204, 204));
        searchBox.setText("Enter name...");
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });
        searchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchBoxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBoxKeyReleased(evt);
            }
        });
        jPanel1.add(searchBox);
        searchBox.setBounds(820, 60, 200, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Search :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(750, 60, 60, 20);

        Name.setForeground(new java.awt.Color(204, 204, 204));
        Name.setText("Enter name...");
        Name.setToolTipText("");
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameKeyPressed(evt);
            }
        });
        jPanel1.add(Name);
        Name.setBounds(100, 230, 170, 30);

        jLabel4.setText("CustomerID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(750, 230, 90, 20);

        jLabel5.setText("Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(750, 260, 80, 10);

        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(750, 290, 80, 20);

        jLabel7.setText("Phone NO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(750, 320, 90, 20);

        jLabel8.setText("NIC NO");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(750, 350, 80, 20);

        UCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UCustomerIDActionPerformed(evt);
            }
        });
        jPanel1.add(UCustomerID);
        UCustomerID.setBounds(850, 230, 170, 26);

        UName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UNameKeyTyped(evt);
            }
        });
        jPanel1.add(UName);
        UName.setBounds(849, 260, 170, 26);
        jPanel1.add(UAdress);
        UAdress.setBounds(849, 290, 170, 26);

        UPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                UPhoneFocusLost(evt);
            }
        });
        UPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UPhoneKeyTyped(evt);
            }
        });
        jPanel1.add(UPhone);
        UPhone.setBounds(849, 320, 170, 26);

        UNIC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                UNICFocusLost(evt);
            }
        });
        jPanel1.add(UNIC);
        UNIC.setBounds(849, 350, 170, 26);

        PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer/vap_2767044009.png"))); // NOI18N
        jPanel1.add(PIC);
        PIC.setBounds(0, 10, 1070, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        try {
            String value1 = UCustomerID.getText();
            String value2 = UName.getText();
            String value3 = UAdress.getText();
            String value4 = UPhone.getText();
            String value5 = UNIC.getText();

            String sql = "update Details set CustomerID= '" + value1 + "', Name='" + value2 + "', Adress='" + value3 + "', Phoneno='" + value4 + "', NICNO='" + value5 + "' where CustomerID = '" + value1 + "'";
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        UName.setText(null);
        UAdress.setText(null);
        UPhone.setText(null);
        UNIC.setText(null);
        UCustomerID.setText(null);
        
        fetch();

    }//GEN-LAST:event_UpdateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String sql = "delete from Details where Name =?";

        try {
            pst = con.prepareStatement(sql);

            pst.setString(1, Name.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
        

        String sql2 = "delete from Status where Name =?";

        try {
            pst = con.prepareStatement(sql);

            pst.setString(1, Name.getText());

            pst.execute();
            //JOptionPane.showMessageDialog(null, "Deleted");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        String sql3 = "delete from Loayalty where Name =?";

        try {
            pst = con.prepareStatement(sql);

            pst.setString(1, Name.getText());

            pst.execute();
            //JOptionPane.showMessageDialog(null, "Deleted");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }// TODO add your handling code here:
        fetch();
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        main frm = new main();
        frm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Registration().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new Loayalty().setVisible(true);  
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new Status().setVisible(true);    
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new Report().setVisible(true);  
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Exit application?")==JOptionPane.OK_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxActionPerformed

    private void searchBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBoxKeyPressed
        DefaultTableModel table = (DefaultTableModel) Details.getModel();
        String search = searchBox.getText().toLowerCase().toUpperCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        Details.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxKeyPressed

    private void searchBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBoxKeyReleased

    }//GEN-LAST:event_searchBoxKeyReleased

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyPressed
        DefaultTableModel table = (DefaultTableModel) Details.getModel();
        String search = Name.getText().toLowerCase().toUpperCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        Details.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));        // TODO add your handling code here:
    }//GEN-LAST:event_NameKeyPressed

    private void DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailsMouseClicked
        // TODO add your handling code here:
        int index = Details.getSelectedRow();

        TableModel model = Details.getModel();

        String CustomerID = model.getValueAt(index, 5).toString();
        String Name = model.getValueAt(index, 0).toString();
        String Adress = model.getValueAt(index, 1).toString();
        String NIC = model.getValueAt(index, 3).toString();
        String Phone = model.getValueAt(index, 2).toString();

        UCustomerID.setText(CustomerID);
        UName.setText(Name);
        UAdress.setText(Adress);
        UNIC.setText(NIC);
        UPhone.setText(Phone);
    }//GEN-LAST:event_DetailsMouseClicked

    private void UCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UCustomerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UCustomerIDActionPerformed

    private void UNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_UNameKeyPressed

    private void UNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UNameKeyTyped
            char c = evt.getKeyChar();
        if (!(((Character.isLetter(c)))|| (c==KeyEvent.VK_BACKSPACE)
            || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_SPACE) )) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_UNameKeyTyped

    private void UPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UPhoneKeyTyped
       char c = evt.getKeyChar();
        if (!((Character.isDigit(c)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if ((UPhone.getText() + evt.getKeyChar()).length() > 10) {
        evt.consume();
    }
        
// TODO add your handling code here:
    }//GEN-LAST:event_UPhoneKeyTyped

    private void UPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UPhoneFocusLost
         if(!(UPhone.getText().trim().matches("^[0]{1}[0-9]{9}$"))) {
            JOptionPane.showMessageDialog(null, "Enter valid phone number ");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_UPhoneFocusLost

    private void UNICFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UNICFocusLost
    if (!(UNIC.getText().trim().matches("^[0-9]{9}[vVxX]$"))) {
            JOptionPane.showMessageDialog(null, "Invalid NIC ");
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_UNICFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Details;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel PIC;
    private javax.swing.JTextField UAdress;
    private javax.swing.JTextField UCustomerID;
    private javax.swing.JTextField UNIC;
    private javax.swing.JTextField UName;
    private javax.swing.JTextField UPhone;
    private javax.swing.JButton Update;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchBox;
    // End of variables declaration//GEN-END:variables
}
