package Customer;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rukshan
 */
public class Registration extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Registration
     */
    public Registration() {
        con = sql_connect.connectDB();
        initComponents();
        this.setLocationRelativeTo(null);
        Date now = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        RegDate.setText(dateFormat.format(now));
        
    }

    private void clearFields() {
        Name.setText(null);
        Adress.setText(null);
        Phoneno.setText(null);
        NICNO.setText(null);
        CustomerID.setText(null);
        RegDate.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CustomerID = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Adress = new javax.swing.JTextField();
        Phoneno = new javax.swing.JTextField();
        NICNO = new javax.swing.JTextField();
        ServiceType = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Status = new javax.swing.JTextField();
        RegDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Customer Registration");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 10, 280, 29);

        jLabel3.setText("Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 60, 20);

        jLabel4.setText("Adress:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 94, 50, 30);

        jLabel5.setText("Phone no:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 140, 60, 30);

        jLabel6.setText("NIC No:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 180, 50, 30);

        jLabel7.setText("Service Item:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 224, 70, 20);

        jLabel8.setText("Customer ID:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 270, 90, 20);

        jLabel9.setText("Date:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 350, 70, 20);

        CustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerIDActionPerformed(evt);
            }
        });
        jPanel1.add(CustomerID);
        CustomerID.setBounds(90, 260, 270, 30);

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameKeyTyped(evt);
            }
        });
        jPanel1.add(Name);
        Name.setBounds(90, 60, 270, 30);

        Adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdressActionPerformed(evt);
            }
        });
        jPanel1.add(Adress);
        Adress.setBounds(90, 100, 270, 30);

        Phoneno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhonenoFocusLost(evt);
            }
        });
        Phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhonenoActionPerformed(evt);
            }
        });
        Phoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PhonenoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhonenoKeyTyped(evt);
            }
        });
        jPanel1.add(Phoneno);
        Phoneno.setBounds(90, 140, 270, 30);

        NICNO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NICNOFocusLost(evt);
            }
        });
        NICNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICNOActionPerformed(evt);
            }
        });
        NICNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NICNOKeyTyped(evt);
            }
        });
        jPanel1.add(NICNO);
        NICNO.setBounds(90, 180, 270, 30);

        ServiceType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROOM AC", "AUTO AC" }));
        ServiceType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceTypeActionPerformed(evt);
            }
        });
        jPanel1.add(ServiceType);
        ServiceType.setBounds(90, 220, 270, 30);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(100, 410, 73, 29);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(190, 410, 59, 29);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(250, 410, 73, 29);

        jButton8.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton8.setText("Report");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(420, 280, 241, 23);

        jButton5.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton5.setText("Customer Details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(420, 130, 241, 23);

        jButton7.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton7.setText("Loayalties");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(420, 230, 241, 23);

        jButton6.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton6.setText("Active /Inactive member");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(420, 180, 241, 23);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("**USE CAPITAL LETTERS ONLY");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 30, 240, 30);

        jLabel11.setText("Status");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 310, 70, 20);

        Status.setEditable(false);
        Status.setText("Active");
        jPanel1.add(Status);
        Status.setBounds(90, 310, 270, 26);

        RegDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegDateActionPerformed(evt);
            }
        });
        jPanel1.add(RegDate);
        RegDate.setBounds(90, 360, 270, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer/vap_2767044009.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerIDActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void AdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdressActionPerformed

    private void PhonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhonenoActionPerformed
        // TODO add your handling code here:
        int PhoneNo = Phoneno.getText().length();
        if (PhoneNo > 11 || PhoneNo < 10) {
            JOptionPane.showMessageDialog(null, "Enter valid phone number");
        }
    }//GEN-LAST:event_PhonenoActionPerformed

    private void NICNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NICNOActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String d = new String(RegDate.getText()); 
        try {
            
                    
            String sql = "INSERT INTO Details (Name, Adress, Phoneno, NICNO, ServiceType, CustomerID, Date)values (?,?,?,?,?,?,?)";
            pst = con.prepareStatement(sql);
            pst.setString(1, Name.getText());
            pst.setString(2, Adress.getText());
            pst.setInt(3, Integer.parseInt(Phoneno.getText()));
            pst.setString(4, NICNO.getText());
            pst.setString(5, ServiceType.getSelectedItem().toString());
            pst.setInt(6, Integer.parseInt(CustomerID.getText()));
            pst.setString(7, d);

            pst.execute();
            JOptionPane.showMessageDialog(null, "saved");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

        try {
            String sql = "INSERT INTO Status (Name, Customer_ID, Status)values (?,?,?)";
            pst = con.prepareStatement(sql);
            pst.setString(1, Name.getText());
            pst.setInt(2, Integer.parseInt(CustomerID.getText()));
            pst.setString(3, Status.getText());

            pst.execute();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            String sql = "INSERT INTO Loayalty (Name, Customer_ID, Date)values (?,?,?)";
            pst = con.prepareStatement(sql);
            pst.setString(1, Name.getText());
            pst.setInt(2, Integer.parseInt(CustomerID.getText()));
            pst.setString(3, d);

            pst.execute();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        clearFields();
    }//GEN-LAST:event_saveActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Details().setVisible(true);   
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new Loayalty().setVisible(true);        
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new Status().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new Report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Exit application?")==JOptionPane.OK_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        main frm = new main();
        frm.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ServiceTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceTypeActionPerformed

    }//GEN-LAST:event_ServiceTypeActionPerformed

    private void PhonenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhonenoKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)))) {
            getToolkit().beep();
            evt.consume();
        }
        
        if ((Phoneno.getText() + evt.getKeyChar()).length() > 10) {
        evt.consume();
    }


    }//GEN-LAST:event_PhonenoKeyTyped

    private void NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(((Character.isLetter(c)))|| (c==KeyEvent.VK_BACKSPACE)
            || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_SPACE) )) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_NameKeyTyped

    private void NICNOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICNOKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NICNOKeyTyped

    private void NICNOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NICNOFocusLost
        // TODO add your handling code here:
        if (!(NICNO.getText().trim().matches("^[0-9]{9}[vVxX]$"))) {
            JOptionPane.showMessageDialog(null, "Invalid NIC ");
        }
    }//GEN-LAST:event_NICNOFocusLost

    private void PhonenoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhonenoFocusLost
        // TODO add your handling code here:
        if(!(Phoneno.getText().trim().matches("^[0]{1}[0-9]{9}$"))) {
            JOptionPane.showMessageDialog(null, "Enter valid phone number ");
        }
    }//GEN-LAST:event_PhonenoFocusLost

    private void PhonenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhonenoKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PhonenoKeyReleased

    private void RegDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adress;
    private javax.swing.JTextField CustomerID;
    private javax.swing.JTextField NICNO;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Phoneno;
    private javax.swing.JTextField RegDate;
    private javax.swing.JComboBox<String> ServiceType;
    private javax.swing.JTextField Status;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

}
