/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OrderTable;

import static com.sun.org.apache.bcel.internal.util.SecuritySupport.getResourceAsStream;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vageesha
 */
public class OrderDelete extends javax.swing.JFrame {

    /**
     * Creates new form OrderDelete
     */
    public void OrderDeleteInit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JTableHeader header = jTable1.getTableHeader();
        header.setBackground(Color.DARK_GRAY);
        header.setForeground(Color.white);
        header.setPreferredSize(new Dimension(100, 40));
        jLabel1 = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        searchtext = new javax.swing.JTextField();
        searchtext.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();
                }
            }
        });

        DocumentListener documentListener = new DocumentListener() {
            public void changedUpdate(DocumentEvent documentEvent) {

            }
            public void insertUpdate(DocumentEvent documentEvent) {

                TableRowSorter <TableModel> sorter = new TableRowSorter <TableModel>(((DefaultTableModel) jTable1.getModel())); 
                sorter.setRowFilter(RowFilter.regexFilter(searchtext.getText()));

                jTable1.setRowSorter(sorter);

            }
            public void removeUpdate(DocumentEvent documentEvent) {

                TableRowSorter <TableModel> sorter = new TableRowSorter <TableModel>(((DefaultTableModel) jTable1.getModel())); 
                sorter.setRowFilter(RowFilter.regexFilter(searchtext.getText()));

                jTable1.setRowSorter(sorter);

            }
        };

        searchtext.getDocument().addDocumentListener(documentListener);
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBackground(new java.awt.Color(147, 151, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CheckBox", "Order ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        try {
            Connection conn = DatabaseConnection.connect();
            PreparedStatement DBOUTPUT = conn.prepareStatement("SELECT orderID FROM orders");
            ResultSet RS = DBOUTPUT.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            while(RS.next())
            {

                model.addRow(new Object[]{false,RS.getString("orderID")});
            }
            conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        JTableUtilities.setCellsAlignment(jTable1, SwingConstants.CENTER,1);

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 48)); // NOI18N
        jLabel1.setText("Order Deletion");

        Delete.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.setPreferredSize(new java.awt.Dimension(142, 67));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Back.setText("Back");
        Back.setPreferredSize(new java.awt.Dimension(142, 67));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        searchtext.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        searchtext.setMaximumSize(new java.awt.Dimension(50, 36));
        searchtext.setPreferredSize(new java.awt.Dimension(50, 36));

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel2.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addGap(262, 262, 262))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(searchtext, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchtext, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getRowCount();
        int h=0;
        int count = 0;
        boolean check;
        ArrayList<String> deleArr = new ArrayList<>(); 
        
         while (h < row){
         check= (Boolean) jTable1.getValueAt(h,0); 
        //if chk is true I can read; 
        // if chk is false the execution stopped at the chk assignement; 
        if (check == true){
            deleArr.add(jTable1.getValueAt(h,1).toString());
            count++;
                          }
        h++;
        }
        
         if(count == 0){
             
               PopupModifyError pop = new PopupModifyError();
               BackgroundPanel background = CallBackground.call();
               pop.setContentPane(background);
               pop.PopupOK_Init();
               pop.IncludeTxt("Please Select a Order");
               pop.setSize(515,301);
               pop.setLocationRelativeTo(null);
               pop.setResizable(false);
               pop.setVisible(true);
               pop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         
         }else{
             
         for (int i = 0; i < deleArr.size(); i++) {
         try{
             
         Connection conn = DatabaseConnection.connect();
         PreparedStatement DBOUTPUT16 = conn.prepareStatement("DELETE FROM orders WHERE orderID = ?");
         DBOUTPUT16.setString(1, deleArr.get(i));
         DBOUTPUT16.executeUpdate();
         
         conn.close();
         }catch(Exception e){
             System.out.println(e);
         }
         }
         }
         if(count != 0){
             
               PopupSuccessful pop = new PopupSuccessful();
               BackgroundPanel background = CallBackground.call();
               pop.setContentPane(background);
               pop.PopupOK_Init();
               pop.IncludeTxt("Order/Orders Deleted Successfully");
               pop.setSize(515,301);
               pop.setLocationRelativeTo(null);
               pop.setResizable(false);
               pop.setVisible(true);
               pop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               this.dispose();
         }
         
    }//GEN-LAST:event_DeleteActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
               OrderTable ordertable = new OrderTable();
               BackgroundPanel background = CallBackground.call();
               ordertable.setContentPane(background);
               ordertable.OrderTableInit();
               ordertable.setSize(1220, 1010);
               ordertable.setLocationRelativeTo(null);
               ordertable.setVisible(true);
               ordertable.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                    ordertable.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
                }
               this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
          try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
          
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               OrderDelete orderdelete = new OrderDelete();
               BackgroundPanel background = CallBackground.call();
               orderdelete.setContentPane(background);
               orderdelete.OrderDeleteInit();
               orderdelete.setSize(880,783);
               orderdelete.setLocationRelativeTo(null);
               orderdelete.setResizable(false);
               orderdelete.setVisible(true);
               orderdelete.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                    orderdelete.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchtext;
    // End of variables declaration//GEN-END:variables
}
