/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OrderTable;

import static com.sun.org.apache.bcel.internal.util.SecuritySupport.getResourceAsStream;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vageesha
 */
public class OrderModify extends javax.swing.JFrame {

    /**
     * Creates new form OrderDelete
     */
    public void OrderModifyInit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JTableHeader header = jTable1.getTableHeader();
        header.setBackground(Color.DARK_GRAY);
        header.setForeground(Color.white);
        header.setPreferredSize(new Dimension(100, 40));
        jLabel1 = new javax.swing.JLabel();
        Modify = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        searchtext = new javax.swing.JTextField();
        searchtext.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();
                }
            }
        });

        DocumentListener documentListener = new DocumentListener() {
            public void changedUpdate(DocumentEvent documentEvent) {

            }
            public void insertUpdate(DocumentEvent documentEvent) {

                TableRowSorter <TableModel> sorter = new TableRowSorter <TableModel>(((DefaultTableModel) jTable1.getModel())); 
                sorter.setRowFilter(RowFilter.regexFilter(searchtext.getText()));

                jTable1.setRowSorter(sorter);

            }
            public void removeUpdate(DocumentEvent documentEvent) {

                TableRowSorter <TableModel> sorter = new TableRowSorter <TableModel>(((DefaultTableModel) jTable1.getModel())); 
                sorter.setRowFilter(RowFilter.regexFilter(searchtext.getText()));

                jTable1.setRowSorter(sorter);

            }
        };

        searchtext.getDocument().addDocumentListener(documentListener);
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBackground(new java.awt.Color(147, 151, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CheckBox", "Order ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        try {
            Connection conn = DatabaseConnection.connect();
            PreparedStatement DBOUTPUT = conn.prepareStatement("SELECT orderID FROM orders");
            ResultSet RS = DBOUTPUT.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            while(RS.next())
            {

                model.addRow(new Object[]{false,RS.getString("orderID")});
            }
            conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        JTableUtilities.setCellsAlignment(jTable1, SwingConstants.CENTER,1);

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 48)); // NOI18N
        jLabel1.setText("Order Modify");

        Modify.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Modify.setText("Modify");
        Modify.setPreferredSize(new java.awt.Dimension(142, 67));
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Back.setText("Back");
        Back.setPreferredSize(new java.awt.Dimension(142, 67));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        searchtext.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        searchtext.setMaximumSize(new java.awt.Dimension(50, 36));
        searchtext.setPreferredSize(new java.awt.Dimension(50, 36));
        searchtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel2.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addGap(262, 262, 262))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(searchtext, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchtext, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyActionPerformed
        // TODO add your handling code here:
        
        int row = jTable1.getRowCount();
        int h=0;
        int count = 0;
        boolean check;
        String modify = null; 
        
         while (h < row){
         check= (Boolean) jTable1.getValueAt(h,0); 
         
         if (check == true){
            modify = jTable1.getValueAt(h,1).toString();
            count++;
         }
         
         h++;
         }
         
         
         if(count == 1){
         
             Integer orderID = null;
             String Description = null;
             Date d1 = null;
             Date d2 = null;
             String CustomerName = null;
             String CustomerAddress = null;
             Integer proID = null;
             Integer qty = null;
             String Status =  null;
             Double dis = null;
             Double total = null;
             Double unit = null;
             
         try{
             
         Connection conn = DatabaseConnection.connect();
         PreparedStatement DBOUTPUT17 = conn.prepareStatement("SELECT * FROM orders WHERE orderID = ?");
         DBOUTPUT17.setString(1, modify);
         ResultSet RS = DBOUTPUT17.executeQuery();
         
         if(RS.next()){
             orderID = RS.getInt("orderID");
             Description = RS.getString("description");
             d1 = RS.getDate("orderDate");
             d2 = RS.getDate("orderDueDate");
             CustomerName = RS.getString("customerName");
             CustomerAddress = RS.getString("customerAddress");
             proID = RS.getInt("productID");
             qty = RS.getInt("quantity");
             Status = RS.getString("orderStatus");
             dis = RS.getDouble("discount");
             total = RS.getDouble("totalPrice");
             unit = RS.getDouble("unitPrice");
             
         }
         
         conn.close();
         }catch(Exception e){
             System.out.println(e);
         }
             
               Order_Form orderform = new Order_Form();
               BackgroundPanel background = CallBackground.call();
               orderform.setContentPane(background);
               orderform.Order_Form_Init();
               orderform.OrderModify(orderID,Description,d1,d2,CustomerName,CustomerAddress,proID,qty,Status,dis,total,unit);
               orderform.setLocationRelativeTo(null);
               orderform.setVisible(true);
               orderform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                    orderform.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
                }
               this.dispose();
             
         } 
         else if(count == 0){
             
               PopupModifyError pop = new PopupModifyError();
               BackgroundPanel background = CallBackground.call();
               pop.setContentPane(background);
               pop.PopupOK_Init();
               pop.IncludeTxt("Please Select a Order");
               pop.setSize(515,301);
               pop.setLocationRelativeTo(null);
               pop.setResizable(false);
               pop.setVisible(true);
               pop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         
         }else {
             
               PopupModifyError pop = new PopupModifyError();
               BackgroundPanel background = CallBackground.call();
               pop.setContentPane(background);
               pop.PopupOK_Init();
               pop.IncludeTxt("Please Select Only One Order");
               pop.setSize(515,301);
               pop.setLocationRelativeTo(null);
               pop.setResizable(false);
               pop.setVisible(true);
               pop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         }
         
    }//GEN-LAST:event_ModifyActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
               OrderTable ordertable = new OrderTable();
               BackgroundPanel background = CallBackground.call();
               ordertable.setContentPane(background);
               ordertable.OrderTableInit();
               ordertable.setSize(1220, 1010);
               ordertable.setLocationRelativeTo(null);
               ordertable.setVisible(true);
               ordertable.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                    ordertable.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
                }
               this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void searchtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
          try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
          
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               OrderModify ordermodify = new OrderModify();
               BackgroundPanel background = CallBackground.call();
               ordermodify.setContentPane(background);
               ordermodify.OrderModifyInit();
               ordermodify.setSize(880,783);
               ordermodify.setLocationRelativeTo(null);
               ordermodify.setResizable(false);
               ordermodify.setVisible(true);
               ordermodify.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                    ordermodify.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Modify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchtext;
    // End of variables declaration//GEN-END:variables
}
