/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OrderTable;

import static com.sun.org.apache.bcel.internal.util.SecuritySupport.getResourceAsStream;
import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vageesha
 */
public class OrderTable extends javax.swing.JFrame {
    /**
     * Creates new form OrderTable
     */
    public void OrderTableInit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JTableHeader header = jTable1.getTableHeader();
        header.setBackground(Color.DARK_GRAY);
        header.setForeground(Color.white);
        header.setPreferredSize(new Dimension(100, 40));
        jLabel1 = new javax.swing.JLabel();
        Insert = new javax.swing.JButton();
        Modify = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Report = new javax.swing.JButton();
        View = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        searchtext = new javax.swing.JTextField();
        DocumentListener documentListener = new DocumentListener() {
            public void changedUpdate(DocumentEvent documentEvent) {

            }
            public void insertUpdate(DocumentEvent documentEvent) {

                TableRowSorter <TableModel> sorter = new TableRowSorter <TableModel>(((DefaultTableModel) jTable1.getModel())); 
                sorter.setRowFilter(RowFilter.regexFilter(searchtext.getText()));

                jTable1.setRowSorter(sorter);

            }
            public void removeUpdate(DocumentEvent documentEvent) {

                TableRowSorter <TableModel> sorter = new TableRowSorter <TableModel>(((DefaultTableModel) jTable1.getModel())); 
                sorter.setRowFilter(RowFilter.regexFilter(searchtext.getText()));

                jTable1.setRowSorter(sorter);

            }
        };

        searchtext.getDocument().addDocumentListener(documentListener);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1220, 1010));
        setSize(new java.awt.Dimension(1220, 1010));

        jTable1.setBackground(new java.awt.Color(147, 151, 255));
        jTable1.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Description", "Order Date", "Order Due Date", "Customer Name", "Address", "Product ID", "Quantity", "Status", "Discount", "Total Price", "Unit Price "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        try {
            Connection conn = DatabaseConnection.connect();
            PreparedStatement DBOUTPUT = conn.prepareStatement("SELECT * FROM orders");
            ResultSet RS = DBOUTPUT.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            DateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");

            while(RS.next())
            {
                model.addRow(new Object[]{RS.getInt("orderID"),RS.getString("description"),dateFormat.format(RS.getDate("orderDate")),dateFormat.format(RS.getDate("orderDueDate")),RS.getString("customerName"),RS.getString("customerAddress"),RS.getInt("productID"),RS.getInt("quantity"),RS.getString("orderStatus"),RS.getDouble("discount"),RS.getDouble("totalPrice"),RS.getDouble("unitPrice")});
            }
            conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        JTableUtilities.setCellsAlignment(jTable1, SwingConstants.CENTER,0);
        JTableUtilities.setCellsAlignment(jTable1, SwingConstants.CENTER,6);
        JTableUtilities.setCellsAlignment(jTable1, SwingConstants.CENTER,7);
        JTableUtilities.setCellsAlignment(jTable1, SwingConstants.CENTER,9);

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 48)); // NOI18N
        jLabel1.setText("Orders");

        Insert.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Insert.setText("Insert");
        Insert.setPreferredSize(new java.awt.Dimension(142, 67));
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        Modify.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Modify.setText("Modify");
        Modify.setPreferredSize(new java.awt.Dimension(142, 67));
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.setPreferredSize(new java.awt.Dimension(142, 67));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Report.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Report.setText("Report");
        Report.setPreferredSize(new java.awt.Dimension(142, 67));
        Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportActionPerformed(evt);
            }
        });

        View.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        View.setText("View");
        View.setPreferredSize(new java.awt.Dimension(142, 67));
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.setPreferredSize(new java.awt.Dimension(142, 67));

        searchtext.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        searchtext.setMaximumSize(new java.awt.Dimension(50, 36));
        searchtext.setPreferredSize(new java.awt.Dimension(50, 36));

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel2.setText("Search");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 512, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(374, 374, 374))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(searchtext, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(searchtext, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
               OrderDelete orderdelete = new OrderDelete();
               BackgroundPanel background = CallBackground.call();
               orderdelete.setContentPane(background);
               orderdelete.OrderDeleteInit();
               orderdelete.setSize(880,783);
               orderdelete.setLocationRelativeTo(null);
               orderdelete.setResizable(false);
               orderdelete.setVisible(true);
               orderdelete.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                    orderdelete.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
                }
               this.dispose();
    }//GEN-LAST:event_DeleteActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
               Order_Form orderform = new Order_Form();
               BackgroundPanel background = CallBackground.call();
               orderform.setContentPane(background);
               orderform.Order_Form_Init();
               orderform.setLocationRelativeTo(null);
               orderform.setVisible(true);
               orderform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                    orderform.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
                }
               this.dispose();
    }//GEN-LAST:event_InsertActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
               OrderViewFull orderview = new OrderViewFull();
               BackgroundPanel background = CallBackground.call();
               orderview.setContentPane(background);
               orderview.OrderViewInit();
               orderview.setSize(880,783);
               orderview.setLocationRelativeTo(null);
               orderview.setResizable(false);
               orderview.setVisible(true);
               orderview.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                    orderview.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
                }
               this.dispose();
    }//GEN-LAST:event_ViewActionPerformed

    private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyActionPerformed
        // TODO add your handling code here:
               OrderModify ordermodify = new OrderModify();
               BackgroundPanel background = CallBackground.call();
               ordermodify.setContentPane(background);
               ordermodify.OrderModifyInit();
               ordermodify.setSize(880,783);
               ordermodify.setLocationRelativeTo(null);
               ordermodify.setResizable(false);
               ordermodify.setVisible(true);
               ordermodify.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                try {
                    ordermodify.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
                }
               this.dispose();
    }//GEN-LAST:event_ModifyActionPerformed

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
        // TODO add your handling code here:
               OrderReport orderreport = new OrderReport();
               BackgroundPanel background = CallBackground.call();
               orderreport.setContentPane(background);
               orderreport.OrderReportInit();
               orderreport.setLocationRelativeTo(null);
               orderreport.setVisible(true);
               orderreport.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                try {
                    orderreport.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
                }
               this.dispose();
    }//GEN-LAST:event_ReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               OrderTable ordertable = new OrderTable();
               BackgroundPanel background = CallBackground.call();
               ordertable.setContentPane(background);
               ordertable.OrderTableInit();
               ordertable.setSize(1220, 1010);
               ordertable.setLocationRelativeTo(null);
               ordertable.setVisible(true);
               ordertable.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                try {
                    ordertable.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(OrderTable.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Insert;
    private javax.swing.JButton Modify;
    private javax.swing.JButton Report;
    private javax.swing.JButton View;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchtext;
    // End of variables declaration//GEN-END:variables
}
