/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import com.mysql.cj.protocol.Resultset;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Thushan
 */
public class display extends javax.swing.JFrame {
    Connection con =null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public display() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        IndexNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ItemName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        warrenty = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        capacity = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Qty = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        UnitPrice = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Brand = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        JTableHeader header = jTable.getTableHeader();
        header.setBackground(Color.DARK_GRAY);

        header.setPreferredSize(new Dimension(100, 40));
        jLabel20 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jTabbedPane1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N

        jPanel2.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Product Id");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 80, 210, 40);

        IndexNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndexNoActionPerformed(evt);
            }
        });
        jPanel2.add(IndexNo);
        IndexNo.setBounds(350, 80, 290, 40);

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Product Name");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 160, 260, 50);

        ItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNameActionPerformed(evt);
            }
        });
        jPanel2.add(ItemName);
        ItemName.setBounds(350, 170, 290, 40);

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Brand");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(30, 250, 150, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Warrenty");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(30, 320, 180, 50);
        jPanel2.add(warrenty);
        warrenty.setBounds(350, 320, 290, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Capacity");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 390, 200, 50);
        jPanel2.add(capacity);
        capacity.setBounds(350, 390, 290, 40);

        jLabel17.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Qty");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(30, 470, 100, 40);
        jPanel2.add(Qty);
        Qty.setBounds(350, 470, 290, 40);

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Unit Price");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(30, 540, 220, 70);
        jPanel2.add(UnitPrice);
        UnitPrice.setBounds(350, 550, 290, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 204));
        jButton4.setText("Add");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(350, 610, 130, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 204));
        jButton5.setText("Reset");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(520, 610, 130, 40);

        Brand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "LG", "Singer", "Galaxy", "Hitachi", "Haier", "KenStar", "Panasonic ", "Whirlpool", "Toshiba", "Sony", "Lenovo", "Samsung" }));
        Brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrandActionPerformed(evt);
            }
        });
        jPanel2.add(Brand);
        Brand.setBounds(350, 240, 290, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thushan\\Desktop\\Itp project\\Add.jpg")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(1100, 750));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, -200, 710, 1090);

        jTabbedPane1.addTab("Add", jPanel2);

        jPanel4.setLayout(null);

        jButton1.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 51));
        jButton1.setText("DELETE");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(350, 480, 240, 70);

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Product Id  :-");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 260, 300, 120);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(jLabel21);
        jLabel21.setBounds(380, 290, 250, 70);

        jLabel22.setFont(new java.awt.Font("Papyrus", 1, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 204, 255));
        jLabel22.setText("Please select the row from the table to delete.");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(10, 50, 660, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thushan\\Desktop\\Itp project\\view.jpg")); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(-20, -10, 740, 730);

        jTabbedPane1.addTab("delete", jPanel4);

        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Product Id");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(40, 80, 210, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product Name");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 160, 260, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Brand");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(40, 250, 150, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Warrenty");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(40, 330, 180, 50);

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Capacity");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(40, 410, 200, 50);

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Qty");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(40, 480, 100, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Unit Price");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(40, 550, 220, 70);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(jTextField2);
        jTextField2.setBounds(360, 70, 300, 40);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTextField3);
        jTextField3.setBounds(360, 160, 300, 40);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTextField5);
        jTextField5.setBounds(360, 330, 300, 40);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTextField6);
        jTextField6.setBounds(360, 410, 300, 40);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTextField7);
        jTextField7.setBounds(360, 480, 300, 40);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jTextField8);
        jTextField8.setBounds(360, 560, 300, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Update");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(370, 640, 130, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("Reset");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(520, 640, 140, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "LG", "Singer", "Galaxy", "Hitachi", "Haier", "KenStar", "Panasonic ", "Whirlpool", "Toshiba", "Sony", "Lenovo", "Samsung" }));
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(360, 242, 300, 40);

        jLabel23.setFont(new java.awt.Font("Papyrus", 1, 22)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 255, 255));
        jLabel23.setText("Please select the row from the table to update.");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(50, 30, 610, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thushan\\Desktop\\Itp project\\update.jpg")); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, -30, 710, 790);

        jTabbedPane1.addTab("Update", jPanel3);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 150, 714, 750);

        jTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Brand", "Warrenty", "Capacity", "Qty", "Unit Price"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(802, 170, 840, 737);

        jLabel20.setFont(new java.awt.Font("Papyrus", 1, 60)); // NOI18N
        jLabel20.setText("Modify Inventory");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(40, 20, 550, 130);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("Back to Main");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(650, 930, 300, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(2, -4, 1690, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // back to main
        main m = new main();
        m.setSize(1500,1000);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        //Uppdate-table mouse click
          DefaultTableModel model = (DefaultTableModel)jTable.getModel();
          int selectedRowIndex = jTable.getSelectedRow();
          
          jLabel21.setText(model.getValueAt(selectedRowIndex, 0).toString());
          jTextField2.setText(model.getValueAt(selectedRowIndex, 0).toString());
          jTextField3.setText(model.getValueAt(selectedRowIndex, 1).toString());
          jComboBox2.setSelectedItem(model.getValueAt(selectedRowIndex, 2).toString());
          jTextField5.setText(model.getValueAt(selectedRowIndex, 3).toString());
          jTextField6.setText(model.getValueAt(selectedRowIndex, 4).toString());
          jTextField7.setText(model.getValueAt(selectedRowIndex, 5).toString());
          jTextField8.setText(model.getValueAt(selectedRowIndex, 6).toString());
       
    }//GEN-LAST:event_jTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // uPDATE-RESET

        jTextField3.setText("");
        jComboBox2.setSelectedItem("None");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Update Button

        try{

              Connection con = DatabaseConnection.connect();
            String sql = "UPDATE Inventory SET ItemName=?, Brand=?, warrenty=?, capacity=?, Qty=?, UnitPrice=? WHERE IndexNo=?";

            pst = con.prepareStatement(sql);

            pst.setString(2,jTextField3.getText());
            pst.setString(3,jComboBox2.getSelectedItem().toString());
            pst.setString(4,jTextField5.getText());
            pst.setString(5,jTextField6.getText());
            pst.setString(6,jTextField7.getText());
            pst.setString(7,jTextField8.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Update successfully");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, "Some fields are empty or incorrect.Try again!!!!");
        }
        showTableData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //delete button

        int delete=JOptionPane.showConfirmDialog(null, "Do you really want to delete?","Delete Items",JOptionPane.YES_NO_OPTION);
        if(delete == 0){

            Connection con = DatabaseConnection.connect();
            String sql = "DELETE FROM Inventory WHERE IndexNo =?";

            try{

                pst = con.prepareStatement(sql);
                pst.setString(1,jLabel21.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Delete successful");
                jLabel21.setText("");

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                jLabel21.setText("");

            }
            showTableData();
        }
        else{
            JOptionPane.showMessageDialog(null, "Delete Unsuccessful");
            jLabel21.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrandActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // add-reset
        IndexNo.setText("");
        ItemName.setText("");
        Brand.setSelectedItem("None");
        warrenty.setText("");
        capacity.setText("");
        Qty.setText("");
        UnitPrice.setText("");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Insert Button
        try{
            String sql = "INSERT INTO Inventory "
            +"(IndexNo, ItemName, Brand, warrenty, capacity, Qty, UnitPrice)"
            +"VALUES(?,?,?,?,?,?,?)";

            Connection con = DatabaseConnection.connect();
            pst = con.prepareStatement(sql);
            pst.setString(1,IndexNo.getText());
            pst.setString(2,ItemName.getText());
            pst.setString(3,Brand.getSelectedItem().toString());
            pst.setString(4,warrenty.getText());
            pst.setString(5,capacity.getText());
            pst.setString(6,Qty.getText());
            pst.setString(7,UnitPrice.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "inserted successfully");

        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null, "Some fields are empty or incorrect.Try again!!!!");

        }

        showTableData();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNameActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_ItemNameActionPerformed

    private void IndexNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndexNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IndexNoActionPerformed

            public void showTableData(){
            try{
                Connection con = DatabaseConnection.connect();
                String sql = "SELECT * FROM Inventory";
                pst = con.prepareStatement(sql);
                rs=pst.executeQuery();
                jTable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                display dis = new display();
                dis.setSize(1700,1500);
                dis.setResizable(false);
                dis.setVisible(true);
                dis.setLocationRelativeTo(null);
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Brand;
    private javax.swing.JTextField IndexNo;
    private javax.swing.JTextField ItemName;
    private javax.swing.JTextField Qty;
    private javax.swing.JTextField UnitPrice;
    private javax.swing.JTextField capacity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField warrenty;
    // End of variables declaration//GEN-END:variables
}
